export const AppRoutes = {
  HOME: "/",
  LOGIN: "/login",
  POSITIONS: "/positions",
  QUESTIONNAIRES: "/questionnaires",
  PROFILE: "/profile",
  REGISTRATION: "/registration/:positionId",
  EXAM: "/exam",

  ADMIN_ROOT: "/admin/*",
  ADMIN_VACANCIES: "/admin/vacancies",
  ADMIN_VACANCY_DESIGNER: "/admin/vacancies/:id/designer",
  ADMIN_VACANCY_EDIT: "/admin/vacancies/:id/edit",
  ADMIN_APPLICANTS: "/admin/applicants",
  ADMIN_TEMPLATES: "/admin/templates",
  ADMIN_TEMPLATE_DESIGNER: "/admin/templates/:id/designer",
  ADMIN_QUESTIONNAIRES: "/admin/questionnaires",
  ADMIN_QUESTIONNAIRES_DESIGNER: "/admin/questionnaires/:id/designer",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_TEST_RESULTS: "/admin/test-results",
  ADMIN_TEST_RESULT_DETAIL: "/admin/test-results/:id",

  SUBPATH_VACANCIES: "vacancies",
  SUBPATH_DESIGNER: "vacancies/:id/designer",
  SUBPATH_EDIT: "vacancies/:id/edit",
  SUBPATH_APPLICANTS: "applicants",
  SUBPATH_TEMPLATES: "templates",
  SUBPATH_QUESTIONNAIRES: "questionnaires",
  SUBPATH_TEST_RESULTS: "test-results",
} as const;
